### ISSUE TITLE
Unit Test Failure Notifications Not Being Sent Out

### ISSUE THREAD

**Issue by pdalbenzio** [tcplugins/tcPrettyEmail#2]
First, thank you very much for the excellent plugin. Your e-mail notifications are MUCH nicer than the built-in ones.

Recently, we upgraded to TeamCity 9.1.6 from 8.1.4, there seems to be one specific scenario where email notifications are not going out to my team: when a build fails because of failing unit tests. It does seem, that after I adjusted the template location using your wiki documentation, that all other e-mails are being sent. It appears that only when a build fails from a failing unit test(s) that it's NOT going out. All e-mails worked before our upgrade to 9.1.6.

I turned on DEBUG logging in TeamCity and it looks like there's a NullPointerException in tcPretty:

[2016-03-31 09:52:56,396]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailContentBuilder :: StartDate : Thu Mar 31 09:50:32 EDT 2016 
[2016-03-31 09:52:56,396]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailContentBuilder :: FinishDate : null 
[2016-03-31 09:52:56,396]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailContentBuilder :: Duration : 144 
[2016-03-31 09:52:56,416]   WARN -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: Could not assemble the BuildFailed prettyemail for bt60 See DEBUG output and/or STDOUT for Stacktrace 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: Attempting to send email using the following configuration 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: from-address: me@github.com 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: from-name   : TeamCity Alert Service 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: host        : ********** 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: port        : **** 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: username    : DOMAIN\user_name
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: starttls-enabled: false 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: password    : HIDDEN 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: template-path  : C:\TeamCity\buildServer\config\tcPrettyEmail_Templates\templates 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: attachment-path: null 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - PrettyEmailNotificator :: attach-images  : true 
[2016-03-31 09:52:56,416]  DEBUG -   jetbrains.buildServer.SERVER - Invocation of method 'getShortTextForWeb' in  class prettyemailer.teamcity.PrettyEmailTestBlockBean threw exception class java.lang.NullPointerException : null 
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getShortTextForWeb' in  class prettyemailer.teamcity.PrettyEmailTestBlockBean threw exception class java.lang.NullPointerException : null
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:246)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:175)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:220)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:55)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:166)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:114)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:55)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:89)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:55)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:89)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:181)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:114)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
	at org.apache.velocity.Template.merge(Template.java:256)
	at prettyemailer.teamcity.PrettyEmailMimeMessageHelper.generateEmail(PrettyEmailMimeMessageHelper.java:51)
	at prettyemailer.teamcity.PrettyEmailNotificator.doNotifications(PrettyEmailNotificator.java:173)
	at prettyemailer.teamcity.PrettyEmailNotificator.notifyBuildFailed(PrettyEmailNotificator.java:232)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.notifyBuildFailureWatchers(UserRulesAwareNotificationListener.java:166)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.buildFailed(UserRulesAwareNotificationListener.java:260)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener.buildFailed(UserRulesAwareNotificationListener.java:36)
	at jetbrains.buildServer.notification.NotificationProcessor$4.call(NotificationProcessor.java:2)
	at jetbrains.buildServer.notification.NotificationProcessor$18.run(NotificationProcessor.java:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thank you very much for any help you can provide!

**Comment by netwolfuk** [comment]
Thanks so much for reporting this. It is now fixed. 
Please download and try version 0.9.34.0

**Comment by pdalbenzio** [comment]
Downloaded and implemented; things look good for me; thanks again!

**Comment by netwolfuk** [comment]
You're welcome. Sorry it took a while to get it done.

**Comment by pdalbenzio** [comment]
Not a problem! I appreciate your OSS work; I know you probably have many other things going on.
